project:
  type: book

book:
  title: "quarto_ex1"
  chapters:
    - index.qmd
    - chap2.qmd

format:
  pdf:
    include-in-header:
      text: |
        \usepackage{fancyhdr}
        \pagestyle{fancy}
        \fancyfoot[R]{Right Footer\\Line 2 Right Footer}
        \fancyfoot[L]{Left Footer\\Line 2 Left Footer}

editor: visual

